"""Add backtest runs and metrics tables

Revision ID: 1684ead76317
Revises: 5c42e05bed9c
Create Date: 2026-04-10 00:43:49.376577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1684ead76317'
down_revision: Union[str, Sequence[str], None] = '5c42e05bed9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('strategy_name', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('interval', sa.String(), nullable=False),
        sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('initial_capital', sa.Float(), nullable=False),
        sa.Column('final_capital', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('details', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    
    op.create_table('backtest_metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('backtest_id', sa.Integer(), nullable=False),
        sa.Column('metric_name', sa.String(), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['backtest_id'], ['backtest_runs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_metrics_id'), 'backtest_metrics', ['id'], unique=False)
    
    # Add interval column to existing ohlc_bars table
    op.add_column('ohlc_bars', sa.Column('interval', sa.String(), nullable=False, server_default='5m'))
    op.create_index(op.f('ix_ohlc_bars_interval'), 'ohlc_bars', ['interval'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_metrics_id'), table_name='backtest_metrics')
    op.drop_table('backtest_metrics')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
