"""add orchestration run records table

Revision ID: 2399a07ef477
Revises: 24bc2237a221
Create Date: 2026-05-11 01:25:13.887760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2399a07ef477'
down_revision: Union[str, Sequence[str], None] = '24bc2237a221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestration_run_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('selected_symbols_count', sa.Integer(), nullable=False),
    sa.Column('ready_symbols_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.String(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orchestration_run_type_created', 'orchestration_run_records', ['run_type', 'created_ts'], unique=False)
    op.create_index(op.f('ix_orchestration_run_records_id'), 'orchestration_run_records', ['id'], unique=False)
    op.create_index(op.f('ix_orchestration_run_records_run_type'), 'orchestration_run_records', ['run_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orchestration_run_records_run_type'), table_name='orchestration_run_records')
    op.drop_index(op.f('ix_orchestration_run_records_id'), table_name='orchestration_run_records')
    op.drop_index('idx_orchestration_run_type_created', table_name='orchestration_run_records')
    op.drop_table('orchestration_run_records')
    # ### end Alembic commands ###
