"""add_trained_model_records_table

Revision ID: 24bc2237a221
Revises: dd37cb9d5d90
Create Date: 2026-05-11 00:31:10.590886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc2237a221'
down_revision: Union[str, Sequence[str], None] = 'dd37cb9d5d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trained_model_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('trainer_run_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_registry_lookup', 'trained_model_records', ['symbol', 'interval', 'model_type', 'created_ts'], unique=False)
    op.create_index(op.f('ix_trained_model_records_id'), 'trained_model_records', ['id'], unique=False)
    op.create_index(op.f('ix_trained_model_records_interval'), 'trained_model_records', ['interval'], unique=False)
    op.create_index(op.f('ix_trained_model_records_model_type'), 'trained_model_records', ['model_type'], unique=False)
    op.create_index(op.f('ix_trained_model_records_symbol'), 'trained_model_records', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trained_model_records_symbol'), table_name='trained_model_records')
    op.drop_index(op.f('ix_trained_model_records_model_type'), table_name='trained_model_records')
    op.drop_index(op.f('ix_trained_model_records_interval'), table_name='trained_model_records')
    op.drop_index(op.f('ix_trained_model_records_id'), table_name='trained_model_records')
    op.drop_index('idx_model_registry_lookup', table_name='trained_model_records')
    op.drop_table('trained_model_records')
    # ### end Alembic commands ###
