"""Add news and sentiment tables

Revision ID: 4f6b7df8680a
Revises: efae6a1ac11d
Create Date: 2026-04-10 00:26:34.206919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6b7df8680a'
down_revision: Union[str, Sequence[str], None] = 'efae6a1ac11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('summary', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('published_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ingested_ts', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_items_id'), 'news_items', ['id'], unique=False)
    
    op.create_table('news_sentiment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('news_id', sa.Integer(), nullable=False),
        sa.Column('sentiment_score', sa.Float(), nullable=False),
        sa.Column('sentiment_label', sa.String(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_id'), 'news_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_news_id'), 'news_sentiment', ['news_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiment_news_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_id'), table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_index(op.f('ix_news_items_id'), table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
