"""Add decision and alert tables

Revision ID: 5c42e05bed9c
Revises: f46590153689
Create Date: 2026-04-10 00:39:40.649037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c42e05bed9c'
down_revision: Union[str, Sequence[str], None] = 'f46590153689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('interval', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('alert_type', sa.String(), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('importance', sa.Float(), nullable=False),
        sa.Column('delivered_channels', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_records_id'), 'alert_records', ['id'], unique=False)
    op.create_index(op.f('ix_alert_records_symbol'), 'alert_records', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_records_timestamp'), 'alert_records', ['timestamp'], unique=False)
    
    op.create_table('decision_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('interval', sa.String(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('decision_label', sa.String(), nullable=False),
        sa.Column('decision_score', sa.Float(), nullable=False),
        sa.Column('price_direction', sa.String(), nullable=True),
        sa.Column('price_confidence', sa.Float(), nullable=True),
        sa.Column('rl_action', sa.String(), nullable=True),
        sa.Column('rl_confidence', sa.Float(), nullable=True),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('sentiment_label', sa.String(), nullable=True),
        sa.Column('options_signal_label', sa.String(), nullable=True),
        sa.Column('options_pcr', sa.Float(), nullable=True),
        sa.Column('options_max_pain_strike', sa.Float(), nullable=True),
        sa.Column('raw_payload', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_id'), 'decision_records', ['id'], unique=False)
    op.create_index(op.f('ix_decision_records_symbol'), 'decision_records', ['symbol'], unique=False)
    op.create_index(op.f('ix_decision_records_timestamp'), 'decision_records', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_records_timestamp'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_symbol'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_alert_records_timestamp'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_symbol'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_id'), table_name='alert_records')
    op.drop_table('alert_records')
    # ### end Alembic commands ###
