"""add_execution_override_records

Revision ID: 5d6f22998e82
Revises: 2399a07ef477
Create Date: 2026-05-11 01:44:24.155974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6f22998e82'
down_revision: Union[str, Sequence[str], None] = '2399a07ef477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_override_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('override_action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_override_lookup', 'execution_override_records', ['symbol', 'interval', 'is_active', 'created_ts'], unique=False)
    op.create_index(op.f('ix_execution_override_records_id'), 'execution_override_records', ['id'], unique=False)
    op.create_index(op.f('ix_execution_override_records_interval'), 'execution_override_records', ['interval'], unique=False)
    op.create_index(op.f('ix_execution_override_records_symbol'), 'execution_override_records', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_override_records_symbol'), table_name='execution_override_records')
    op.drop_index(op.f('ix_execution_override_records_interval'), table_name='execution_override_records')
    op.drop_index(op.f('ix_execution_override_records_id'), table_name='execution_override_records')
    op.drop_index('idx_execution_override_lookup', table_name='execution_override_records')
    op.drop_table('execution_override_records')
    # ### end Alembic commands ###
