"""Initial migration

Revision ID: b728a74416b8
Revises: 
Create Date: 2026-04-09 20:52:51.808817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b728a74416b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_bars',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('exchange', sa.String(), nullable=False),
        sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('open', sa.Float(), nullable=False),
        sa.Column('high', sa.Float(), nullable=False),
        sa.Column('low', sa.Float(), nullable=False),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('vwap', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ohlc_bars_exchange'), 'ohlc_bars', ['exchange'], unique=False)
    op.create_index(op.f('ix_ohlc_bars_id'), 'ohlc_bars', ['id'], unique=False)
    op.create_index(op.f('ix_ohlc_bars_symbol'), 'ohlc_bars', ['symbol'], unique=False)
    op.create_index('idx_symbol_start_ts', 'ohlc_bars', ['symbol', 'start_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbol_start_ts', table_name='ohlc_bars')
    op.drop_index(op.f('ix_ohlc_bars_symbol'), table_name='ohlc_bars')
    op.drop_index(op.f('ix_ohlc_bars_id'), table_name='ohlc_bars')
    op.drop_index(op.f('ix_ohlc_bars_exchange'), table_name='ohlc_bars')
    op.drop_table('ohlc_bars')
    # ### end Alembic commands ###
