"""Add instrument_master table

Revision ID: dd37cb9d5d90
Revises: 1684ead76317
Create Date: 2026-05-10 23:41:24.277420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd37cb9d5d90'
down_revision: Union[str, Sequence[str], None] = '1684ead76317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('instrument_key', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('underlying_symbol', sa.String(), nullable=True),
    sa.Column('underlying_key', sa.String(), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_master_exchange'), 'instrument_master', ['exchange'], unique=False)
    op.create_index(op.f('ix_instrument_master_id'), 'instrument_master', ['id'], unique=False)
    op.create_index(op.f('ix_instrument_master_instrument_key'), 'instrument_master', ['instrument_key'], unique=True)
    op.create_index(op.f('ix_instrument_master_instrument_type'), 'instrument_master', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_instrument_master_name'), 'instrument_master', ['name'], unique=False)
    op.create_index(op.f('ix_instrument_master_segment'), 'instrument_master', ['segment'], unique=False)
    op.create_index(op.f('ix_instrument_master_trading_symbol'), 'instrument_master', ['trading_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrument_master_trading_symbol'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_segment'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_name'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_instrument_type'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_instrument_key'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_id'), table_name='instrument_master')
    op.drop_index(op.f('ix_instrument_master_exchange'), table_name='instrument_master')
    op.drop_table('instrument_master')
    # ### end Alembic commands ###
