"""Add price_features table

Revision ID: efae6a1ac11d
Revises: b728a74416b8
Create Date: 2026-04-09 21:04:14.723495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efae6a1ac11d'
down_revision: Union[str, Sequence[str], None] = 'b728a74416b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_features',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
        sa.Column('interval', sa.String(), nullable=False),
        sa.Column('rsi_14', sa.Float(), nullable=True),
        sa.Column('vwap', sa.Float(), nullable=True),
        sa.Column('ema_short', sa.Float(), nullable=True),
        sa.Column('ema_long', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('symbol', 'ts', 'interval', name='uq_symbol_ts_interval')
    )
    op.create_index(op.f('ix_price_features_id'), 'price_features', ['id'], unique=False)
    op.create_index(op.f('ix_price_features_symbol'), 'price_features', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_features_ts'), 'price_features', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_features_ts'), table_name='price_features')
    op.drop_index(op.f('ix_price_features_symbol'), table_name='price_features')
    op.drop_index(op.f('ix_price_features_id'), table_name='price_features')
    op.drop_table('price_features')
    # ### end Alembic commands ###
