"""Add options snapshots and signals tables

Revision ID: f46590153689
Revises: 4f6b7df8680a
Create Date: 2026-04-10 00:33:39.260327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46590153689'
down_revision: Union[str, Sequence[str], None] = '4f6b7df8680a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
        sa.Column('strike', sa.Float(), nullable=False),
        sa.Column('option_type', sa.String(), nullable=False),
        sa.Column('open_interest', sa.Float(), nullable=False),
        sa.Column('change_in_oi', sa.Float(), nullable=True),
        sa.Column('volume', sa.Float(), nullable=True),
        sa.Column('last_traded_price', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opt_symbol_expiry_strike_type_ts', 'option_snapshots', ['symbol', 'expiry', 'strike', 'option_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_option_snapshots_expiry'), 'option_snapshots', ['expiry'], unique=False)
    op.create_index(op.f('ix_option_snapshots_id'), 'option_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_option_snapshots_strike'), 'option_snapshots', ['strike'], unique=False)
    op.create_index(op.f('ix_option_snapshots_symbol'), 'option_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_option_snapshots_timestamp'), 'option_snapshots', ['timestamp'], unique=False)
    
    op.create_table('option_signals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('pcr', sa.Float(), nullable=True),
        sa.Column('max_pain_strike', sa.Float(), nullable=True),
        sa.Column('call_oi_total', sa.Float(), nullable=True),
        sa.Column('put_oi_total', sa.Float(), nullable=True),
        sa.Column('signal_label', sa.String(), nullable=True),
        sa.Column('signal_strength', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_signals_expiry'), 'option_signals', ['expiry'], unique=False)
    op.create_index(op.f('ix_option_signals_id'), 'option_signals', ['id'], unique=False)
    op.create_index(op.f('ix_option_signals_symbol'), 'option_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_option_signals_timestamp'), 'option_signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_signals_timestamp'), table_name='option_signals')
    op.drop_index(op.f('ix_option_signals_symbol'), table_name='option_signals')
    op.drop_index(op.f('ix_option_signals_id'), table_name='option_signals')
    op.drop_index(op.f('ix_option_signals_expiry'), table_name='option_signals')
    op.drop_table('option_signals')
    op.drop_index(op.f('ix_option_snapshots_timestamp'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_symbol'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_strike'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_id'), table_name='option_snapshots')
    op.drop_index(op.f('ix_option_snapshots_expiry'), table_name='option_snapshots')
    op.drop_index('idx_opt_symbol_expiry_strike_type_ts', table_name='option_snapshots')
    op.drop_table('option_snapshots')
    # ### end Alembic commands ###
