"""Add execution_dispatch_records table

Revision ID: fbdeebd62f22
Revises: 5d6f22998e82
Create Date: 2026-05-11 11:34:59.715680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdeebd62f22'
down_revision: Union[str, Sequence[str], None] = '5d6f22998e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_dispatch_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('dispatched_action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_dispatch_source')
    )
    op.create_index('idx_dispatch_symbol_interval_created', 'execution_dispatch_records', ['symbol', 'interval', 'created_ts'], unique=False)
    op.create_index(op.f('ix_execution_dispatch_records_id'), 'execution_dispatch_records', ['id'], unique=False)
    op.create_index(op.f('ix_execution_dispatch_records_interval'), 'execution_dispatch_records', ['interval'], unique=False)
    op.create_index(op.f('ix_execution_dispatch_records_symbol'), 'execution_dispatch_records', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_dispatch_records_symbol'), table_name='execution_dispatch_records')
    op.drop_index(op.f('ix_execution_dispatch_records_interval'), table_name='execution_dispatch_records')
    op.drop_index(op.f('ix_execution_dispatch_records_id'), table_name='execution_dispatch_records')
    op.drop_index('idx_dispatch_symbol_interval_created', table_name='execution_dispatch_records')
    op.drop_table('execution_dispatch_records')
    # ### end Alembic commands ###
